name: Deploy_Dev
on:
  pull_request:
    branches:
      - dev
      
  push:
    branches:
      - dev
      - feature/*


run-name: ${{ github.actor }}

env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read
  
jobs:
# -------------------- Security Scan --------------------
  tfsec-scan:
    name: tfsec Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./environments/dev
          soft_fail: false


 #----------------------------Terraform Init & Plan Job----------------------------------
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest 
    needs: tfsec-scan
    environment: Dev1
    defaults:
      run:
        working-directory: ./environments/dev
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        id: Init
        run: |          
          terraform init \
            -backend-config="resource_group_name=backend-dev" \
            -backend-config="storage_account_name=backendstgukdev" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=dev.tfstate"
        


      - name: Terraform fmt
        id: Fmt
        run: terraform fmt
        

      - name: Terraform Validate
        id: Validate
        run: terraform validate
        

      - name: Terraform Plan
        id: Plan
        run: terraform plan -no-color -input=false -out=tfplan
        #continue-on-error: true
        
         

  #----------------------------Terraform Apply Job---------------------------------- 


  terraform-apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    needs: terraform-plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/dev
    
    
    environment: Dev   # approval gate

  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        id: Init
        run: |          
          terraform init \
            -backend-config="resource_group_name=backend-dev" \
            -backend-config="storage_account_name=backendstgukdev" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=dev.tfstate"
        

      - name: Terraform Apply
        id: Apply
        run: terraform apply --auto-approve
        
        
        





